package testit;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tietorakenteet.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.18 15:23:20 // Generated by ComTest
 *
 */
public class ValineTest {



  // Generated by ComTest BEGIN
  /** testToString137 */
  @Test
  public void testToString137() {    // Valine: 137
    Valine valine = new Valine(); 
    valine.parse("Teppo|1|pallo|hyvä"); 
    assertEquals("From: Valine line: 140", "Teppo|1|pallo|hyvä", valine.toString()); 
  } // Generated by ComTest END
}